import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/shared/nav";
import CarouselSection from "../components/home/carousel";
import Destinations from "../components/home/destinations";
import About from "../components/home/about";
import Contact from "../components/home/contact";
import FooterComponent from "../components/shared/footerComponent";
import {Container} from "react-bootstrap";
import Packages from "../components/home/packages";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>3ala Feen</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <CarouselSection/>
            <Destinations/>
            <About/>
            <Packages/>
            <Contact/>
        </div>
    )
}
